### ISSUE TITLE
unable to use _init function in other modules

### ISSUE THREAD

**Issue by afternoon2** [afternoon2/gradient-base#2]
While making the TravisCI build the following error appears during the tests:

```javascript
AIL ./index.test.js
  Test suite failed to run
    Cannot find module './Base' from 'init.js'
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/gradient-base/src/init.js:1:1)
```

Looks like either the `./Base` should be written as `./base` (like the filename) and/or the src and docs directories should be removed from the npm package.

**Comment by afternoon2** [comment]
fixed by v.1.0.4
